version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: reports-system-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laapak_report_system
      MYSQL_USER: laapak
      MYSQL_PASSWORD: laapaksql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reports-network

  app:
    build:
      context: ../../
      dockerfile: scripts/deployment/Dockerfile
    container_name: reports-system-app-1
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    networks:
      - reports-network
    volumes:
      - ../../:/app

volumes:
  db_data:


networks:
  reports-network:
    driver: bridge
